# Generated by Django 4.0.4 on 2022-05-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=5000)),
                ('url', models.CharField(max_length=200)),
                ('cluster', models.IntegerField()),
                ('site_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=10000)),
                ('url', models.CharField(max_length=200)),
                ('salary', models.CharField(max_length=200)),
                ('cluster', models.IntegerField()),
            ],
        ),
    ]
