# Generated by Django 4.0.4 on 2022-06-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_course_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cluster',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='content',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='site_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='cluster',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='content',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
